// 365 consejos únicos sobre perfumes — uno por día del año
export const PERFUME_TIPS: readonly string[] = [
  "Día 1: Consejo del día: en verano, prioriza fragancias amaderada para sentirte fresco sin saturar el ambiente.",
  "Día 2: ¿Sabías que Tom Ford tiene opciones ideales para una boda? Pregúntanos cuál te conviene hoy.",
  "Día 3: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que gourmand se desarrolle mejor.",
  "Día 4: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 5: Para junio, las notas especiada suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 6: Rota entre dos fragancias a la semana: una gourmand y otra oud para no acostumbrar a quienes te rodean.",
  "Día 7: Un Eau de Parfum de Hermès puede durar 8 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 8: Antes de reuniones importantes, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 9: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Hermès y otras casas.",
  "Día 10: En invierno, combina una base especiada con ropa de tonos neutros para un estilo coherente.",
  "Día 11: Las fragancias oud suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 12: Si buscas algo para regalar, Hugo Boss tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 13: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más oud.",
  "Día 14: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas gourmand.",
  "Día 15: Para la noche, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 16: Un perfume oriental de Calvin Klein puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 17: En viajes, lleva frascos de 7 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 18: Las notas de salida duran minutos; la verdadera personalidad aromática aparece tras 15–30 minutos.",
  "Día 19: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 20: Para el calor de marzo, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 21: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Byredo y casas reconocidas.",
  "Día 22: Una fragancia aromática madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 23: En invierno, las cítrica con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 24: Para hombre, Carolina Herrera ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 25: Para mujer, las almizclada de Chanel destacan en primavera y en eventos diurnos.",
  "Día 26: El perfume unisex de Creed es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 27: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 28: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 29: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 17 a 29 meses.",
  "Día 30: Para una boda, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 31: Explora la familia almizclada si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 32: Consejo del día: en primavera, prioriza fragancias fougère para sentirte fresco sin saturar el ambiente.",
  "Día 33: ¿Sabías que Creed tiene opciones ideales para el día? Pregúntanos cuál te conviene hoy.",
  "Día 34: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que cuero se desarrolle mejor.",
  "Día 35: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 36: Para enero, las notas oud suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 37: Rota entre dos fragancias a la semana: una cuero y otra oriental para no acostumbrar a quienes te rodean.",
  "Día 38: Un Eau de Parfum de Bulgari puede durar 9 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 39: Antes de una entrevista, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 40: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Bulgari y otras casas.",
  "Día 41: En otoño, combina una base oud con ropa de tonos neutros para un estilo coherente.",
  "Día 42: Las fragancias oriental suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 43: Si buscas algo para regalar, Calvin Klein tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 44: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más oriental.",
  "Día 45: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas cuero.",
  "Día 46: Para salidas casuales, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 47: Un perfume chipre de Paco Rabanne puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 48: En viajes, lleva frascos de 5 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 49: Las notas de salida duran minutos; la verdadera personalidad frutal aparece tras 15–30 minutos.",
  "Día 50: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 51: Para el calor de octubre, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 52: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Le Labo y casas reconocidas.",
  "Día 53: Una fragancia frutal madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 54: En invierno, las gourmand con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 55: Para hombre, Valentino ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 56: Para mujer, las amaderada de Dior destacan en primavera y en eventos diurnos.",
  "Día 57: El perfume unisex de Armani es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 58: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 59: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 60: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 12 a 24 meses.",
  "Día 61: Para el día, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 62: Explora la familia amaderada si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 63: Consejo del día: en invierno, prioriza fragancias acuática para sentirte fresco sin saturar el ambiente.",
  "Día 64: ¿Sabías que Armani tiene opciones ideales para reuniones importantes? Pregúntanos cuál te conviene hoy.",
  "Día 65: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que almizclada se desarrolle mejor.",
  "Día 66: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 67: Para agosto, las notas oriental suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 68: Rota entre dos fragancias a la semana: una almizclada y otra chipre para no acostumbrar a quienes te rodean.",
  "Día 69: Un Eau de Parfum de Cartier puede durar 10 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 70: Antes de la oficina, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 71: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Cartier y otras casas.",
  "Día 72: En verano, combina una base oriental con ropa de tonos neutros para un estilo coherente.",
  "Día 73: Las fragancias chipre suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 74: Si buscas algo para regalar, Paco Rabanne tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 75: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más chipre.",
  "Día 76: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas almizclada.",
  "Día 77: Para un brunch, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 78: Un perfume aromática de Jean Paul Gaultier puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 79: En viajes, lleva frascos de 6 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 80: Las notas de salida duran minutos; la verdadera personalidad floral aparece tras 15–30 minutos.",
  "Día 81: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 82: Para el calor de mayo, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 83: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Acqua di Parma y casas reconocidas.",
  "Día 84: Una fragancia floral madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 85: En invierno, las cuero con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 86: Para hombre, Burberry ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 87: Para mujer, las fougère de Tom Ford destacan en primavera y en eventos diurnos.",
  "Día 88: El perfume unisex de Versace es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 89: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 90: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 91: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 19 a 31 meses.",
  "Día 92: Para reuniones importantes, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 93: Explora la familia fougère si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 94: Consejo del día: en otoño, prioriza fragancias especiada para sentirte fresco sin saturar el ambiente.",
  "Día 95: ¿Sabías que Versace tiene opciones ideales para una entrevista? Pregúntanos cuál te conviene hoy.",
  "Día 96: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que amaderada se desarrolle mejor.",
  "Día 97: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 98: Para marzo, las notas chipre suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 99: Rota entre dos fragancias a la semana: una amaderada y otra aromática para no acostumbrar a quienes te rodean.",
  "Día 100: Un Eau de Parfum de Montblanc puede durar 6 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 101: Antes de un viaje, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 102: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Montblanc y otras casas.",
  "Día 103: En primavera, combina una base chipre con ropa de tonos neutros para un estilo coherente.",
  "Día 104: Las fragancias aromática suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 105: Si buscas algo para regalar, Jean Paul Gaultier tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 106: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más aromática.",
  "Día 107: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas amaderada.",
  "Día 108: Para la graduación, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 109: Un perfume frutal de Maison Francis Kurkdjian puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 110: En viajes, lleva frascos de 7 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 111: Las notas de salida duran minutos; la verdadera personalidad cítrica aparece tras 15–30 minutos.",
  "Día 112: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 113: Para el calor de diciembre, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 114: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Penhaligon's y casas reconocidas.",
  "Día 115: Una fragancia cítrica madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 116: En invierno, las almizclada con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 117: Para hombre, Chanel ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 118: Para mujer, las acuática de Creed destacan en primavera y en eventos diurnos.",
  "Día 119: El perfume unisex de Gucci es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 120: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 121: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 122: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 14 a 26 meses.",
  "Día 123: Para una entrevista, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 124: Explora la familia acuática si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 125: Consejo del día: en verano, prioriza fragancias oud para sentirte fresco sin saturar el ambiente.",
  "Día 126: ¿Sabías que Gucci tiene opciones ideales para la oficina? Pregúntanos cuál te conviene hoy.",
  "Día 127: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que fougère se desarrolle mejor.",
  "Día 128: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 129: Para octubre, las notas aromática suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 130: Rota entre dos fragancias a la semana: una fougère y otra frutal para no acostumbrar a quienes te rodean.",
  "Día 131: Un Eau de Parfum de Dolce & Gabbana puede durar 7 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 132: Antes de eventos formales, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 133: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Dolce & Gabbana y otras casas.",
  "Día 134: En invierno, combina una base aromática con ropa de tonos neutros para un estilo coherente.",
  "Día 135: Las fragancias frutal suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 136: Si buscas algo para regalar, Maison Francis Kurkdjian tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 137: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más frutal.",
  "Día 138: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas fougère.",
  "Día 139: Para una boda, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 140: Un perfume floral de Byredo puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 141: En viajes, lleva frascos de 5 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 142: Las notas de salida duran minutos; la verdadera personalidad gourmand aparece tras 15–30 minutos.",
  "Día 143: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 144: Para el calor de julio, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 145: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Viktor & Rolf y casas reconocidas.",
  "Día 146: Una fragancia gourmand madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 147: En invierno, las amaderada con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 148: Para hombre, Dior ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 149: Para mujer, las especiada de Armani destacan en primavera y en eventos diurnos.",
  "Día 150: El perfume unisex de Prada es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 151: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 152: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 153: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 21 a 33 meses.",
  "Día 154: Para la oficina, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 155: Explora la familia especiada si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 156: Consejo del día: en primavera, prioriza fragancias oriental para sentirte fresco sin saturar el ambiente.",
  "Día 157: ¿Sabías que Prada tiene opciones ideales para un viaje? Pregúntanos cuál te conviene hoy.",
  "Día 158: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que acuática se desarrolle mejor.",
  "Día 159: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 160: Para mayo, las notas frutal suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 161: Rota entre dos fragancias a la semana: una acuática y otra floral para no acostumbrar a quienes te rodean.",
  "Día 162: Un Eau de Parfum de Givenchy puede durar 8 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 163: Antes de el gimnasio, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 164: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Givenchy y otras casas.",
  "Día 165: En otoño, combina una base frutal con ropa de tonos neutros para un estilo coherente.",
  "Día 166: Las fragancias floral suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 167: Si buscas algo para regalar, Byredo tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 168: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más floral.",
  "Día 169: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas acuática.",
  "Día 170: Para el día, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 171: Un perfume cítrica de Le Labo puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 172: En viajes, lleva frascos de 6 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 173: Las notas de salida duran minutos; la verdadera personalidad cuero aparece tras 15–30 minutos.",
  "Día 174: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 175: Para el calor de febrero, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 176: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Narciso Rodriguez y casas reconocidas.",
  "Día 177: Una fragancia cuero madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 178: En invierno, las fougère con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 179: Para hombre, Tom Ford ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 180: Para mujer, las oud de Versace destacan en primavera y en eventos diurnos.",
  "Día 181: El perfume unisex de YSL es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 182: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 183: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 184: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 16 a 28 meses.",
  "Día 185: Para un viaje, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 186: Explora la familia oud si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 187: Consejo del día: en invierno, prioriza fragancias chipre para sentirte fresco sin saturar el ambiente.",
  "Día 188: ¿Sabías que YSL tiene opciones ideales para eventos formales? Pregúntanos cuál te conviene hoy.",
  "Día 189: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que especiada se desarrolle mejor.",
  "Día 190: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 191: Para diciembre, las notas floral suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 192: Rota entre dos fragancias a la semana: una especiada y otra cítrica para no acostumbrar a quienes te rodean.",
  "Día 193: Un Eau de Parfum de Lancôme puede durar 9 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 194: Antes de un aniversario, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 195: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Lancôme y otras casas.",
  "Día 196: En verano, combina una base floral con ropa de tonos neutros para un estilo coherente.",
  "Día 197: Las fragancias cítrica suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 198: Si buscas algo para regalar, Le Labo tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 199: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más cítrica.",
  "Día 200: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas especiada.",
  "Día 201: Para reuniones importantes, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 202: Un perfume gourmand de Acqua di Parma puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 203: En viajes, lleva frascos de 7 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 204: Las notas de salida duran minutos; la verdadera personalidad almizclada aparece tras 15–30 minutos.",
  "Día 205: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 206: Para el calor de septiembre, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 207: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Carolina Herrera y casas reconocidas.",
  "Día 208: Una fragancia almizclada madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 209: En invierno, las acuática con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 210: Para hombre, Creed ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 211: Para mujer, las oriental de Gucci destacan en primavera y en eventos diurnos.",
  "Día 212: El perfume unisex de Hermès es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 213: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 214: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 215: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 23 a 35 meses.",
  "Día 216: Para eventos formales, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 217: Explora la familia oriental si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 218: Consejo del día: en otoño, prioriza fragancias aromática para sentirte fresco sin saturar el ambiente.",
  "Día 219: ¿Sabías que Hermès tiene opciones ideales para el gimnasio? Pregúntanos cuál te conviene hoy.",
  "Día 220: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que oud se desarrolle mejor.",
  "Día 221: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 222: Para julio, las notas cítrica suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 223: Rota entre dos fragancias a la semana: una oud y otra gourmand para no acostumbrar a quienes te rodean.",
  "Día 224: Un Eau de Parfum de Hugo Boss puede durar 10 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 225: Antes de una cita, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 226: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Hugo Boss y otras casas.",
  "Día 227: En primavera, combina una base cítrica con ropa de tonos neutros para un estilo coherente.",
  "Día 228: Las fragancias gourmand suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 229: Si buscas algo para regalar, Acqua di Parma tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 230: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más gourmand.",
  "Día 231: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas oud.",
  "Día 232: Para una entrevista, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 233: Un perfume cuero de Penhaligon's puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 234: En viajes, lleva frascos de 5 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 235: Las notas de salida duran minutos; la verdadera personalidad amaderada aparece tras 15–30 minutos.",
  "Día 236: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 237: Para el calor de abril, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 238: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Valentino y casas reconocidas.",
  "Día 239: Una fragancia amaderada madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 240: En invierno, las especiada con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 241: Para hombre, Armani ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 242: Para mujer, las chipre de Prada destacan en primavera y en eventos diurnos.",
  "Día 243: El perfume unisex de Bulgari es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 244: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 245: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 246: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 18 a 30 meses.",
  "Día 247: Para el gimnasio, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 248: Explora la familia chipre si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 249: Consejo del día: en verano, prioriza fragancias frutal para sentirte fresco sin saturar el ambiente.",
  "Día 250: ¿Sabías que Bulgari tiene opciones ideales para un aniversario? Pregúntanos cuál te conviene hoy.",
  "Día 251: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que oriental se desarrolle mejor.",
  "Día 252: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 253: Para febrero, las notas gourmand suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 254: Rota entre dos fragancias a la semana: una oriental y otra cuero para no acostumbrar a quienes te rodean.",
  "Día 255: Un Eau de Parfum de Calvin Klein puede durar 6 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 256: Antes de la noche, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 257: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Calvin Klein y otras casas.",
  "Día 258: En invierno, combina una base gourmand con ropa de tonos neutros para un estilo coherente.",
  "Día 259: Las fragancias cuero suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 260: Si buscas algo para regalar, Penhaligon's tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 261: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más cuero.",
  "Día 262: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas oriental.",
  "Día 263: Para la oficina, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 264: Un perfume almizclada de Viktor & Rolf puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 265: En viajes, lleva frascos de 6 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 266: Las notas de salida duran minutos; la verdadera personalidad fougère aparece tras 15–30 minutos.",
  "Día 267: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 268: Para el calor de noviembre, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 269: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Burberry y casas reconocidas.",
  "Día 270: Una fragancia fougère madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 271: En invierno, las oud con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 272: Para hombre, Versace ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 273: Para mujer, las aromática de YSL destacan en primavera y en eventos diurnos.",
  "Día 274: El perfume unisex de Cartier es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 275: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 276: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 277: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 13 a 25 meses.",
  "Día 278: Para un aniversario, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 279: Explora la familia aromática si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 280: Consejo del día: en primavera, prioriza fragancias floral para sentirte fresco sin saturar el ambiente.",
  "Día 281: ¿Sabías que Cartier tiene opciones ideales para una cita? Pregúntanos cuál te conviene hoy.",
  "Día 282: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que chipre se desarrolle mejor.",
  "Día 283: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 284: Para septiembre, las notas cuero suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 285: Rota entre dos fragancias a la semana: una chipre y otra almizclada para no acostumbrar a quienes te rodean.",
  "Día 286: Un Eau de Parfum de Paco Rabanne puede durar 7 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 287: Antes de salidas casuales, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 288: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Paco Rabanne y otras casas.",
  "Día 289: En otoño, combina una base cuero con ropa de tonos neutros para un estilo coherente.",
  "Día 290: Las fragancias almizclada suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 291: Si buscas algo para regalar, Viktor & Rolf tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 292: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más almizclada.",
  "Día 293: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas chipre.",
  "Día 294: Para un viaje, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 295: Un perfume amaderada de Narciso Rodriguez puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 296: En viajes, lleva frascos de 7 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 297: Las notas de salida duran minutos; la verdadera personalidad acuática aparece tras 15–30 minutos.",
  "Día 298: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 299: Para el calor de junio, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 300: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Chanel y casas reconocidas.",
  "Día 301: Una fragancia acuática madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 302: En invierno, las oriental con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 303: Para hombre, Gucci ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 304: Para mujer, las frutal de Hermès destacan en primavera y en eventos diurnos.",
  "Día 305: El perfume unisex de Montblanc es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 306: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 307: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 308: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 20 a 32 meses.",
  "Día 309: Para una cita, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 310: Explora la familia frutal si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 311: Consejo del día: en invierno, prioriza fragancias cítrica para sentirte fresco sin saturar el ambiente.",
  "Día 312: ¿Sabías que Montblanc tiene opciones ideales para la noche? Pregúntanos cuál te conviene hoy.",
  "Día 313: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que aromática se desarrolle mejor.",
  "Día 314: En clima caluroso como el de Nuevo Laredo, 2 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 315: Para abril, las notas almizclada suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 316: Rota entre dos fragancias a la semana: una aromática y otra amaderada para no acostumbrar a quienes te rodean.",
  "Día 317: Un Eau de Parfum de Jean Paul Gaultier puede durar 8 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 318: Antes de un brunch, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 319: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Jean Paul Gaultier y otras casas.",
  "Día 320: En verano, combina una base almizclada con ropa de tonos neutros para un estilo coherente.",
  "Día 321: Las fragancias amaderada suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 322: Si buscas algo para regalar, Narciso Rodriguez tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 323: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más amaderada.",
  "Día 324: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas aromática.",
  "Día 325: Para eventos formales, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 326: Un perfume fougère de Carolina Herrera puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 327: En viajes, lleva frascos de 5 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 328: Las notas de salida duran minutos; la verdadera personalidad especiada aparece tras 15–30 minutos.",
  "Día 329: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 330: Para el calor de enero, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 331: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Dior y casas reconocidas.",
  "Día 332: Una fragancia especiada madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 333: En invierno, las chipre con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 334: Para hombre, Prada ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco.",
  "Día 335: Para mujer, las floral de Bulgari destacan en primavera y en eventos diurnos.",
  "Día 336: El perfume unisex de Dolce & Gabbana es ideal si compartes estilo con tu pareja o prefieres aromas sin etiqueta de género.",
  "Día 337: Reaplica a mediodía solo si es necesario: en la zona fronteriza, una EDT ligera puede ser más cómoda que un parfum intenso.",
  "Día 338: La ropa de algodón retiene mejor el perfume que las fibras sintéticas; pruébalo en la nuca y en la solapa.",
  "Día 339: Si coleccionas, anota la fecha de apertura: un EDP abierto rinde óptimo durante 15 a 27 meses.",
  "Día 340: Para la noche, menos es más: una bruma fina proyecta confianza mejor que empaparse de aroma.",
  "Día 341: Explora la familia floral si te cansaste de lo dulce: hay opciones elegantes y sobrias.",
  "Día 342: Consejo del día: en otoño, prioriza fragancias gourmand para sentirte fresco sin saturar el ambiente.",
  "Día 343: ¿Sabías que Dolce & Gabbana tiene opciones ideales para salidas casuales? Pregúntanos cuál te conviene hoy.",
  "Día 344: Aplica tu perfume en puntos de pulso — muñecas, cuello y detrás de las orejas — para que frutal se desarrolle mejor.",
  "Día 345: En clima caluroso como el de Nuevo Laredo, 3 pulverizaciones bastan; el calor amplifica la intensidad del aroma.",
  "Día 346: Para noviembre, las notas amaderada suelen rendir mejor durante el día y proyectar con elegancia.",
  "Día 347: Rota entre dos fragancias a la semana: una frutal y otra fougère para no acostumbrar a quienes te rodean.",
  "Día 348: Un Eau de Parfum de Maison Francis Kurkdjian puede durar 9 horas; úsalo por la mañana y evita reaplicar en exceso.",
  "Día 349: Antes de la graduación, prueba tu perfume en la piel: la química personal cambia cómo huele cada fragancia.",
  "Día 350: Guarda tus perfumes lejos del sol y del baño; el calor y la humedad acortan la vida útil de Maison Francis Kurkdjian y otras casas.",
  "Día 351: En primavera, combina una base amaderada con ropa de tonos neutros para un estilo coherente.",
  "Día 352: Las fragancias fougère suelen ser mejores para la noche; reserva las cítricas para la mañana.",
  "Día 353: Si buscas algo para regalar, Carolina Herrera tiene clásicos que casi nunca fallan en cumpleaños y fechas especiales.",
  "Día 354: Hidrata la piel antes de perfumar: sobre piel humectada, el aroma dura más y se percibe más fougère.",
  "Día 355: No frotes las muñecas tras aplicar perfume; eso rompe las moléculas y acorta la duración de notas frutal.",
  "Día 356: Para el gimnasio, elige concentraciones EDP si quieres presencia sin exagerar.",
  "Día 357: Un perfume acuática de Valentino puede ser tu firma olfativa si lo usas con constancia un mes.",
  "Día 358: En viajes, lleva frascos de 6 ml: ocupan poco espacio y te permiten cambiar según el clima del destino.",
  "Día 359: Las notas de salida duran minutos; la verdadera personalidad oud aparece tras 15–30 minutos.",
  "Día 360: Si tu perfume se siente débil, prueba aplicarlo después de la ducha: el vapor abre los poros y fija mejor el aroma.",
  "Día 361: Para el calor de agosto, prefieres acuáticas o cítricas antes que orientales muy densas.",
  "Día 362: Pregunta por dupes legales no: en Jon Al Parfum solo originales de Tom Ford y casas reconocidas.",
  "Día 363: Una fragancia oud madura con el tiempo en tu piel; dale al menos media hora antes de decidir si te gusta.",
  "Día 364: En invierno, las aromática con vainilla o ámbar abrazan el frío y duran más en ropa de manga larga.",
  "Día 365: Para hombre, YSL ofrece líneas versátiles que van de lo casual a lo formal sin cambiar de frasco."
] as const;

const TIMEZONE = "America/Monterrey";

function getLocalDateParts(date: Date) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: TIMEZONE,
    year: "numeric",
    month: "numeric",
    day: "numeric",
  }).formatToParts(date);

  const get = (type: string) =>
    Number(parts.find((part) => part.type === type)?.value ?? 0);

  return { year: get("year"), month: get("month"), day: get("day") };
}

export function getDayOfYear(date: Date = new Date()): number {
  const { year, month, day } = getLocalDateParts(date);
  const current = Date.UTC(year, month - 1, day);
  const start = Date.UTC(year, 0, 0);
  return Math.floor((current - start) / 86400000);
}

export function getDailyPerfumeTip(date: Date = new Date()): string {
  const index = (getDayOfYear(date) - 1) % PERFUME_TIPS.length;
  return PERFUME_TIPS[index];
}
